version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:stable
    steps:
    - checkout
    - run:
        name: Install build dependencies
        command: apt-get update && apt-get install -y g++ cmake git libgmp-dev libcgal-dev
    - run:
        name: Build and install dependencies
        command: make dep
    - run:
        name: Make
        command: make release
    - run:
        name: Make unit tests
        command: make release -C unittest
    - run:
        name: Create testing directory
        command: mkdir -p bin/testing/test
    - run:
        name: Run unit tests
        command: ./bin/test --xml 2>/dev/null 2>/dev/null | tee bin/testing/test/results.xml
    - store_test_results:
        path: bin/testing
workflows:
  version: 2
  workflow:
    jobs:
    - build
