version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run: apt-get update && apt-get install -y g++ cmake git libgmp-dev libcgal-dev
    - run: ./init.sh
    - run: ./make_release.sh
    - run: ( cd unittest && ./make_release.sh )
    - run: mkdir $CIRCLE_TEST_REPORTS/cmocka
    - run: ./bin/unittest --xml | tee $CIRCLE_TEST_REPORTS/cmocka/results.xml
workflows:
  version: 2
  workflow:
    jobs:
    - build
